name: Free Up Disk Space

# Event trigger (required)
on:
  workflow_dispatch:  # allows you to manually trigger this workflow
  push:               # optional: trigger on push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /home/runner/actions-runner/_work/_temp/*
          sudo rm -rf /home/runner/actions-runner/_work/_runner*
          df -h
